---
id: touch
version: 2
value:
  enabled: true
  uri: '/gateway/api/gateway/touch'
valueDef:
  type: JSON
  #formRef: 'uiserv/form@touch-config-form'
  attributes:
    - id: enabled
      type: BOOLEAN
    - id: uri
